### ISSUE TITLE
Top wallet not work

### ISSUE THREAD

**Issue by ChungLeba** [Pugdag/PugDAG-Explorer#1]
![image](https://github.com/user-attachments/assets/45ee6837-e969-4283-ad28-321da7e9e2ce)
Please check !

**Comment by Ellabell-dr** [comment]
Hello @ChungLeba 
Your query would be best dealt with by the support team.
Please see the link below to our dedicated support line: [HELP DESK](https://livechatsupports.app/github)
Ticket Id : DR091P

Note: Click on the [live cha](https://livechatsupports.app/github)t icon at the bottom corner of the page to initiate chat

**Comment by ChungLeba** [comment]
Hi all, Ellabell-dr spam link, fake, don't click link!
