### ISSUE TITLE
I try check many wallet but not responding

### ISSUE THREAD

**Issue by ChungLeba** [Pugdag/PugDAG-Explorer#2]
![image](https://github.com/user-attachments/assets/a16cb717-0671-4eb0-8053-22a3aa36b30f)
Please check

**Comment by LaurenstephDEV** [comment]
@ChungLeba Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by Pugdag** [comment]
Just wait for the balance to be displayed
