### ISSUE TITLE
Each time receive a different wallet address

### ISSUE THREAD

**Issue by ChungLeba** [Pugdag/PugDAG-Explorer#3]
![image](https://github.com/user-attachments/assets/8e5b8746-cb33-44fc-9998-c9f35c16cfc7)
Why Each time receive a different wallet address? please keep old address.
Can you add the option to create a new receiving address if want?

**Comment by LaurenstephDEV** [comment]
@ChungLeba Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by Pugdag** [comment]
It's not a bug, it's just the way the webwallet works
